# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://rpgbasement.xyz"
baseurl: ""

# Name of website
title: Ролевой Подвал

# Short description of your site
description: Спускайся к нам, мы тут играем в настольные ролевые игры

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Что здесь происходит?: "aboutme"
  Поиск: "search"
  Разделы:
    - Часы Приёма: "https://rpgbasement.xyz/tags/#%D0%A7%D0%B0%D1%81%D1%8B%20%D0%BF%D1%80%D0%B8%D1%91%D0%BC%D0%B0"
    - Принимаем удар на себя: "https://rpgbasement.xyz/tags/#%D0%9F%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D0%BC%20%D1%83%D0%B4%D0%B0%D1%80%20%D0%BD%D0%B0%20%D1%81%D0%B5%D0%B1%D1%8F"
    - Тёмный угол: "https://rpgbasement.xyz/tags/#%D0%A2%D1%91%D0%BC%D0%BD%D1%8B%D0%B9%20%D1%83%D0%B3%D0%BE%D0%BB"
    - Play like a big old badass: "https://rpgbasement.xyz/tags/#Play%20like%20a%20big%20old%20badass"
    - Зайду позже: "https://rpgbasement.xyz/tags/#Зайду позже"
  Другие части Подвала:
    - VK: "https://vk.com/rpgbasement"
    - Telegram: "https://t.me/rpgbasement"
    - Twitch: "https://twitch.tv/rpgbasement"
    - YouTube: "https://www.youtube.com/channel/UCr-09bDJ9wvDxTMmotgOeFg"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/telebasement.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Вундер и Маса

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  podcast: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "rpgbasement.xyz"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-124267599-1"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

# matomo:
#   site_id: "1"
#   uri: "li1715-215.members.linode.com/statz"
#   opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# Staticman support
# staticman:
  # repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  # branch     : # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  # endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  # reCaptcha:
  #   # reCaptcha for Staticman (OPTIONAL)
  #   # If you use reCaptcha, you must also set these parameters in staticman.yml
  #   siteKey  : # Use your own site key, you need to apply for one on Google
  #   secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 0

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Moscow"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 10

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true


# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcastSite: {{url}}

# The cover image for the podcast, will show in search results in iTunes
podcastCoverImg: https://rpgbasement.xyz/podcast/logo.png

# The name of your podcast
podcastTitle: Зайду позже

# About You. For iTunes admin. This information is not displayed on the iTunes Store.
podcastOwner: Ролевой Подвал
podcastEmail: rpgbasement@gmail.com

podcastFeedUrl: https://rpgbasement.xyz/podcast/zp-feed.xml

# See https://www.apple.com/itunes/podcasts/specs.html near the bottom for valid categories
category: Education

podcastAuthor: Ролевой Подвал
podcastDescription: "Услышав какие-то звуки из подвала, очень хочется зайти туда позже. Однако это не тот случай. На связи Ролевой Подвал. Это наш подкаст \"Зайду позже\", где мы обсуждаем настольные ролевые игры во всех их проявлениях: новости, обзоры игр, различныe полезныe статьи и свои мысли. У нас также есть блог https://rpgbasement.xyz, где находятся разные текстовые материалы."
podcastSubtitle: Говорим про настольные ролевые игры во всём их многообразии.

# Don't edit below this line unless you know what you are doing.
# ------------------------------------------------------------------------


# Create a Jekyll collection to handle the episodes
# collections:
# - episodes

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Dockerfile
  - readme.md

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
